### ISSUE TITLE
Required files missing

### ISSUE THREAD

**Issue by WolvenSpectre** [colebob9/FrankenHUD-Builder#1]
I could find and add WGet and 7-zip manually, but the other libraries didn't have to be manually added the last time In installed this and I can't find them from an original source online.  Is it because I am on a new Win 10 install and the firewall is blocking downloads or am I missing something obvious.  Also I did try to run the builder in Admin mode.

**Comment by chlorinezorine** [comment]
Are you sure you downloaded [a release?](https://github.com/colebob9/FrankenHUD-Builder/releases)  I compiled everything you need in that .zip file. Don't download the source. I intentionally left the dependencies out of the repo because it's not my code.

**Comment by WolvenSpectre** [comment]
Sorry... I am such a Maroon!  I accidentally downloaded the code zip and didn't realize it.... thanks!

Update:
I am getting a moved TF2 error.  I have an SSD and I keep so much of my steam library on a secondary drive I just decided to put steam on my secondary drive.  Its been over a decade since I wrote batch files so could you point me to what lines to edit the correct paths without screwing up the Batch file?

**Comment by chlorinezorine** [comment]
Just change every line with the text `%ProgramFiles(x86)%\Steam\steamapps\common\Team Fortress 2\bin\vpk.exe` to where that exe would be on your secondary drive.

**Comment by WolvenSpectre** [comment]
Thanks allot.
